name: Publish Tag Helpers (production)
on:
  push:
    tags:
      - 'v*'
    paths:
      - "**.ts"
      - "**.json"
      - "**.mts"
      - "lib/**"
      - ".github/**.yaml"
permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish Tag Helpers
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Configure CodeArtifact auth
        id: code-artifact-auth
        uses: govuk-once/platform-actions/.github/actions/codeartifact-auth@b4f8bce4ba09bc31301025ff1a5b5daa4973dee6
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}

      - name: Install Deps
        run: pnpm install

      - name: Create .npmrc for publishing config
        run: echo "registry=${{ steps.code-artifact-auth.outputs.registry-url }}" >> .npmrc

      - name: Publish Package to CodeArtifact
        run: pnpm publish --no-git-checks
